version: "3.7"
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USERNAME: secret
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3307:3306"

  redis:
    image: "artifacts.intranet.mckinsey.com/gold-images/redis:6.0"
    user: "1001"
    command: ["redis-server", "--maxmemory 1024m", "--requirepass ReD1Sp455w0rD"]

  holy-basil:
    depends_on:
      - "db"
      - "redis"
    build:
      context: ../MDE_ProposeToWin-holy_basil/.
      args:
        JFROG_USERNAME: <Get from Team>
        JFROG_PASSWORD: <Get from Team>
    ports:
      - "3008:3000"
    environment:
      HOLY_BASIL_DATABASE_USERNAME: secret
      HOLY_BASIL_DATABASE_PASSWORD: secret
      HOLY_BASIL_DATABASE_NAME: secret
      HOLY_BASIL_DATABASE_PORT: 3306
      HOLY_BASIL_DATABASE_HOST: db
      API_PORTAL_HOST: secret
      API_PORTAL_CLIENT_ID: secret
      API_PORTAL_CLIENT_SECRET: secret
      RAILS_ENV: development
      RAILS_MAX_THREADS: 20
      CACHE_URL: 'redis://redis'
    volumes:
      - "../MDE_ProposeToWin-holy_basil/.:/app"

  carom:
    depends_on:
      - "db"
      - "redis"
      - "holy-basil"
    build:
      context: .
      args:
        JFROG_USERNAME: <Get from Team>
        JFROG_PASSWORD: <Get from Team>
    ports:
      - "3006:3000"
    environment:
      CAROM_DATABASE_USERNAME: secret
      CAROM_DATABASE_PASSWORD: secret
      CAROM_DATABASE_NAME: secret
      CAROM_DATABASE_PORT: 3306
      CAROM_DATABASE_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      CACHE_URL: 'redis://redis'
      notify_dev_team_at: "dope_notifications-aaaaeywbsjgnkwuvbslxbaikvu@mckinsey.org.slack.com"
      RAILS_MASTER_KEY: <Get from Team>
    volumes:
      - ".:/app"

volumes:
  db: