name: 02. WORKFLOW dispatch demo
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the image to deploy'
        required: true
        default: ead1d97

  # Dependency to a forking workflow
  workflow_run:
    workflows: [ "01. Checkout, Build And Push on 'mckinsey-elm-dope-docker'" ]
    type:
      - complete
jobs:
  say_hi:
    runs-on: [ linux, PlatformAccelerator ]
    steps:
      - name: Hi
        run: echo "Hi"
      - name: Praveen
        run: echo "${{ github.event.inputs.tag || 'latest}}"